---

platform: linux

image_resource:
  type: docker-image
  source: {repository: ubuntu}

params:
  OPSPW:
  OPSMANIP:
  OPSMAN_URI:
          
inputs:
  - name: pcf-pipelines

run:
  path: pcf-pipelines/tasks/config-opsman-timeout/task.sh
